SELECT * FROM EMP;

SELECT SYSDATE FROM DUAL;

SELECT SYSDATE, SYSDATE-1, SYSDATE+1 FROM DUAL;

SELECT SYSDATE, ADD_MONTHS(SYSDATE,3) FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD') FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD') FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') FROM DUAL;

SELECT SYSDATE, NEXT_DAY(SYSDATE, '월요일'), LAST_DAY(SYSDATE) FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYY'), TO_CHAR(SYSDATE, 'MM'), TO_CHAR(SYSDATE, 'DD'), 
TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') FROM DUAL;

SELECT SAL, TO_CHAR(SAL, '$999,999') AS SAL_달러 FROM EMP;

SELECT SAL, TO_CHAR(SAL, 'L999,999') AS SAL_원 FROM EMP;

SELECT SAL, TO_CHAR(SAL*12, 'L999,999') AS 연봉_원 FROM EMP;

SELECT SAL, TO_CHAR(SAL, 'L999,999') AS SAL_원, LENGTH(SAL) FROM EMP 
ORDER BY LENGTH(SAL) DESC;

SELECT SAL, TO_CHAR(SAL*12, 'L999,999') AS 연봉_원, LENGTH(SAL*12)FROM EMP 
ORDER BY LENGTH(SAL*12) DESC;

SELECT TO_DATE('2026-01-06','YYYY-MM-DD') AS TODATE FROM DUAL;

SELECT ENAME, SAL, NVL(COMM, 0) AS COMMISSION FROM EMP;

SELECT JOB, SUM(SAL) AS "급여 합계" FROM EMP 
GROUP BY JOB;

SELECT DEPTNO, SUM(SAL) AS "급여 합계" FROM EMP 
GROUP BY DEPTNO;

SELECT DEPTNO, JOB, SUM(SAL) AS "급여 합계" FROM EMP 
GROUP BY DEPTNO, JOB;

SELECT DEPTNO, COUNT(*) AS "부서별 인원수" FROM EMP 
GROUP BY DEPTNO;

SELECT JOB, COUNT(*) AS "직책별 인원수" FROM EMP 
GROUP BY JOB;

SELECT JOB, SUM(SAL*12) AS "연봉 합계" FROM EMP 
GROUP BY JOB;

SELECT DEPTNO, SUM(SAL*12) AS "연봉 합계" FROM EMP 
GROUP BY DEPTNO;

SELECT DEPTNO, JOB, SUM(SAL*12) AS "연봉 합계" FROM EMP 
GROUP BY DEPTNO, JOB;

SELECT DEPTNO, JOB, AVG(SAL) FROM EMP 
GROUP BY DEPTNO, JOB 
HAVING AVG(SAL) >= 1000;

SELECT DEPTNO, JOB, AVG(SAL) FROM EMP 
GROUP BY DEPTNO, JOB 
HAVING AVG(SAL) >= 2000;

SELECT DEPTNO, JOB, AVG(SAL) FROM EMP 
GROUP BY DEPTNO, JOB 
HAVING AVG(SAL) <= 3000;

SELECT DEPTNO, JOB, AVG(SAL) FROM EMP 
GROUP BY DEPTNO, JOB 
HAVING AVG(SAL) <= 5000;

SELECT DEPTNO, JOB, AVG(SAL)FROM EMP
GROUP BY DEPTNO, JOB
HAVING AVG(SAL) >= 2000;

SELECT EMPNO, ENAME, HIREDATE, ADD_MONTHS(HIREDATE, 240) AS WORK20YEAR FROM EMP;

SELECT TO_DATE('2024-08-14','YYYY-MM-DD') AS TODATE1, 
TO_DATE('2024/08/14','YYYY/MM/DD') 
AS TODATE2 FROM DUAL;

SELECT EMPNO, ENAME, HIREDATE, TRUNC(SYSDATE - HIREDATE) AS "근무일수" FROM EMP;

SELECT EMPNO, ENAME, HIREDATE, TRUNC(HIREDATE - (SELECT MIN(HIREDATE) FROM EMP)) 
AS "입사차이일수" FROM EMP 
WHERE HIREDATE - (SELECT MIN(HIREDATE) FROM EMP) >= 365 
ORDER BY HIREDATE;

SELECT EMPNO, ENAME, COMM, NVL2(COMM, 'O', 'X'), NVL2(COMM, SAL*12+COMM, SAL*12) 
AS 연봉 FROM EMP;

SELECT EMPNO, ENAME, COMM, NVL2(COMM, 'O', 'X') AS "수령여부1", 
DECODE(COMM, 0, 'X', NULL, 'X', 'O') AS "수령여부2", 
NVL2(COMM, SAL * 12 + COMM, SAL * 12) AS 연봉 FROM EMP;

SELECT EMPNO, ENAME, JOB, SAL, 
DECODE(JOB, 'MANAGER', SAL*1.1, 'SALESMAAN', SAL*1.05, 'ANALYST', SAL, SAL*1.03) 
AS UPSAL FROM EMP;

SELECT EMPNO, ENAME, JOB, SAL, 
 CASE JOB WHEN 'MANAGER' 
 THEN 'NO.1' WHEN 'SALESMAN' 
 THEN 'NO.2' WHEN 'ANALYST'  
 THEN 'NO.3' ELSE 'NO.4' 
 END AS UPSAL FROM EMP;

SELECT EMPNO, ENAME, COMM, CASE WHEN COMM IS NULL
 THEN '해당 사항 없음' WHEN COMM = 0 
 THEN '수당 없음' WHEN COMM > 0 
 THEN '수당 :   ' || 
 COMM END AS COMM_TEXT FROM EMP;