SELECT * FROM EMP;

CREATE TABLE DEPT_TEMP
AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TEMP;

SELECT * FROM EMP, DEPT_TEMP, SALGRADE S;

SELECT EMPNO, ENAME, DEPTNO, DNAME, LOC
  FROM EMP E, DEPT D 
WHERE E.DEPTNO = D.DEPTNO;

SELECT E.EMPNO, E.ENAME, D.DEPTNO, D.DNAME, D.LOC
  FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO;

SELECT E.EMPNO, E.ENAME, D.DEPTNO, D.DNAME, D.LOC
  FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
  AND D.LOC = 'CHICAGO';

SELECT E.EMPNO, E.ENAME, D.DEPTNO, D.DNAME, D.LOC
  FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
  AND D.LOC = 'NEW YORK';

SELECT E.EMPNO, E.ENAME, E.SAL, D.DEPTNO, D.DNAME, D.LOC
    FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
  AND E.SAL<=2500
  AND E.EMPNO<=9999;

SELECT * FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;

SELECT E1.EMPNO, E1.ENAME, E1.MGR, E2.ENAME
  FROM EMP E1, EMP E2 
WHERE E1.MGR = E2.EMPNO;

SELECT E1.EMPNO, E1.ENAME, E1.MGR, E2.ENAME
  FROM EMP E1, EMP E2 
WHERE E1.MGR = E2.EMPNO(+);

SELECT E1.EMPNO, E1.ENAME, E1.MGR, E2.ENAME
  FROM EMP E1, EMP E2 
WHERE E1.MGR(+) = E2.EMPNO;

SELECT E1.EMPNO, E1.ENAME, E1.MGR, 
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
  FROM EMP E1, EMP E2 
WHERE E1.MGR = E2.EMPNO;

SELECT E1.EMPNO, E1.ENAME, E1.MGR,
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
  FROM EMP E1, EMP E2 
WHERE E1.MGR = E2.EMPNO(+);

SELECT E1.EMPNO, E1.ENAME, E1.MGR,
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
   FROM EMP E1, EMP E2 
WHERE E1.MGR(+) = E2.EMPNO;

SELECT * FROM EMP 
WHERE SAL > (SELECT SAL 
            FROM EMP 
            WHERE ENAME = 'JONES');

SELECT * FROM EMP 
WHERE HIREDATE < (SELECT HIREDATE
                  FROM EMP 
                 WHERE ENAME = 'SCOTT');

SELECT E.EMPNO, E.ENAME, E.JOB, E.SAL, D.DEPTNO, D.DNAME, D.LOC
   FROM EMP E, DEPT D 
WHERE E.DEPTNO = D.DEPTNO    
AND E.DEPTNO = 20 
AND E.SAL < (SELECT AVG(SAL)
             FROM EMP);

SELECT * FROM EMP 
WHERE (DEPTNO, SAL) IN (SELECT DEPTNO, MAX(SAL)
                    FROM EMP 
                    GROUP BY DEPTNO); 

SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC 
  FROM (SELECT * FROM EMP WHERE DEPTNO = 10) E10, 
       (SELECT * FROM DEPT) D 
WHERE E10.DEPTNO = D.DEPTNO;

WITH 
E10 AS (SELECT * FROM EMP WHERE DEPTNO = 10), 
D   AS (SELECT * FROM DEPT) 
SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC 
   FROM E10, D 
WHERE E10.DEPTNO = D.DEPTNO;

SELECT EMPNO, ENAME, JOB, SAL,
              (SELECT GRADE
                 FROM SALGRADE
                WHERE E.SAL BETWEEN LOSAL AND HISAL) AS SALGRADE,
                DEPTNO,
              (SELECT DNAME
                FROM DEPT
               WHERE E.DEPTNO = DEPT.DEPTNO) AS DNAME
FROM EMP E;